[package]
name = "rust_port"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22.2"

[dependencies]
itertools = "0.14.0"
rusqlite = "0.37.0"
lalrpop-util = { version = "0.22.2", features = ["lexer", "unicode"] }
logos = "0.15.1"

[dev-dependencies]
tempfile = "3.0"
